# Generated by Django 5.1.3 on 2024-11-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('MG', 'Medicina General'), ('PD', 'Pediatría'), ('GN', 'Ginecología'), ('TR', 'Traumatología'), ('DR', 'Dermatología'), ('OF', 'Oftalmología'), ('OD', 'Odontología'), ('PS', 'Psiquiatría'), ('CR', 'Cardiología')], max_length=2),
        ),
    ]
