# Generated by Django 5.1.3 on 2024-11-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('Medicina General', 'Medicina General'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología'), ('Traumatología', 'Traumatología'), ('Dermatología', 'Dermatología'), ('Oftalmología', 'Oftalmología'), ('Odontología', 'Odontología'), ('Psiquiatría', 'Psiquiatría'), ('Cardiología', 'Cardiología')], max_length=20),
        ),
    ]
