# Generated by Django 5.1.3 on 2024-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
